'use strict';

var m = require('mithril');

var api = {};

// Global API parameters

// The domain name of the API server, dynamically computed from the current app
// domain name so that the API can work locally and on production without
// modification to this source
api.hostname = 'api.' + window.location.hostname;
// The secret key used to authenticate a user signing in
api.secretKey = 'j9Y6iEbYDBCZjebCGd1Q4NvZop1ugLBLf1l5xEqE';
// The access token generated by the server after the user has signed in; used
// to make subsequent requests
api.accessToken = null;

// Return true if the user is currently signed in; otherwise, return false
api.isAuthenticated = function () {
  return (api.accessToken !== null);
};

// Authenticate the user via the given API token (received from the server)
api.authenticate = function (accessToken) {
  api.accessToken = accessToken;
};

// Make any type of HTTP request
api.request = function (method, args) {
  m.request({
    method: method,
    url: api.hostname + args.path,
    data: args.data,
    // Only send the Authorization header once the user has signed in (i.e. when
    // the server sends an access token to the user for their current session)
    headers: api.isAuthenticated() ? {
      'Authorization': api.accessToken
    } : null
  })
  .then(args.onsuccess)
  .catch(args.onerror);
};

// Send a GET request to the server (i.e. retrieve existing entries)
api.get = function (args) {
  api.request('GET', args);
};

// Send a POST request to the server (i.e. update existing entries)
api.post = function (args) {
  api.request('POST', args);
};

// Send a PUT request to the server (i.e. insert new entries)
api.put = function (args) {
  api.request('PUT', args);
};

// Send a DELETE request to the server (i.e. delete new entries)
api.delete = function (args) {
  api.request('DELETE', args);
};

module.exports = api;
